name: Deploy Shopsohere-Ecomms MERN Stack to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # --------------------------
    # Build & Push Backend Image
    # --------------------------
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Backend Image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/shopsohere-ecomms-backend:latest ./backend

    - name: Push Backend Image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/shopsohere-ecomms-backend:latest

    # --------------------------
    # Build & Push Frontend Image
    # --------------------------
    - name: Build Frontend Image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/shopsohere-ecomms-frontend:latest ./frontend

    - name: Push Frontend Image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/shopsohere-ecomms-frontend:latest

    # --------------------------
    # Deploy on VPS via SSH
    # --------------------------
    - name: Deploy on VPS
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /home/princewillopah/DevOps/MERN
          docker-compose pull
          docker-compose up -d --remove-orphans
          docker image prune -f
